name: GaussianEditor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  # for pytorch and support custom C++ extensions
  # for triton
  - lit=17.0.6
  - cmake=3.27.9
  # for faster setup.up building?
  - ninja=1.11.1
  - pip:
    - -r requirements.lock.txt
